name: A workflow for my new Hello World file
on: push

jobs:
  build:
    name: "Hello Actions"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Varun"